/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package invoices;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;


/**
 *
 * @author Dell
 */
public class Invoice extends JFrame {

    /**
     * Creates new form invice
     */
    public Invoice() {
        initComponents();
        
        savefile.setAccelerator(KeyStroke.getKeyStroke('S', KeyEvent.CTRL_DOWN_MASK));
        loadfile.setAccelerator(KeyStroke.getKeyStroke('O', KeyEvent.CTRL_DOWN_MASK));
        
        String [] coulmns = new String[]{
        "NO","Date","Customer","Total"
        };
                model = new DefaultTableModel();
		Object[] coln = {"No.","Date","Customer" , "Total"};
		//final Object[] row = new Object[4];
		model.setColumnIdentifiers(coln);
		table.setModel(model);
    }
 DefaultTableModel model ;

    public void filldata(){  
        
        String [] coulmns = new String[]{
        "NO","Date","Customer","Total"
        };
                model=new DefaultTableModel();
		Object[] coln = {"No.","Date","Customer" , "Total"};
		//final Object[] row = new Object[4];
		model.setColumnIdentifiers(coln);
		table.setModel(model);
		
		if(invoice_no_field.getText().equals("") || datefiled.getText().equals("") || customerfield.getText().equals("") || totalfield.getText().equals("") ) {
			JOptionPane.showMessageDialog(null, "Please Enter all Fields! ");

		}else {
		//inv_Num_label.setText(invoice_no_field.getText());
                    
//		row[0] = invoice_no_field.getText();
//              	row[1] = datefiled.getText();
//		row[2] = customerfield.getText();
//		row[3] = totalfield.getText();
                    model = (DefaultTableModel) table.getModel();
                    model.addRow(new Object [] {invoice_no_field.getText(),datefiled.getText(),
                                               customerfield.getText(),totalfield.getText() });
		
                
		JOptionPane.showMessageDialog(null, "Data Added Successfully ");


		//model.addRow(row);
		invoice_no_field.setText("");
		datefiled.setText("");
		customerfield.setText("");
		totalfield.setText("");
		}
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deleteBTn = new javax.swing.JButton();
        createBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        invoice_no_field = new javax.swing.JTextField();
        datefiled = new javax.swing.JTextField();
        totalfield = new javax.swing.JTextField();
        customerfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        saveBTN = new javax.swing.JButton();
        CancelBTn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadfile = new javax.swing.JMenuItem();
        savefile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Invoioces table");

        deleteBTn.setText("Delete invoice");
        deleteBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTnActionPerformed(evt);
            }
        });

        createBTN.setText("Create new invoice");
        createBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTNActionPerformed(evt);
            }
        });

        jLabel2.setText("Invoice Number");

        jLabel3.setText("Invoice Date");

        jLabel4.setText("Customer Name");

        jLabel5.setText("Invoice total");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        table.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(table);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Invoice Items");

        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        CancelBTn.setText("Cancel");
        CancelBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTnActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane4.setViewportView(table2);

        jMenu1.setText("File");

        loadfile.setMnemonic('l');
        loadfile.setText("Load File");
        loadfile.setActionCommand("L");
        loadfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadfileActionPerformed(evt);
            }
        });
        jMenu1.add(loadfile);

        savefile.setMnemonic('s');
        savefile.setText("Save File");
        savefile.setActionCommand("S");
        savefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savefileActionPerformed(evt);
            }
        });
        jMenu1.add(savefile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(customerfield, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(datefiled, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(invoice_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(deleteBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(CancelBTn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(createBTN)
                    .addContainerGap(841, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invoice_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(datefiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customerfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteBTn)
                            .addComponent(saveBTN)
                            .addComponent(CancelBTn))
                        .addGap(48, 48, 48))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(561, Short.MAX_VALUE)
                    .addComponent(createBTN)
                    .addGap(48, 48, 48)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadfileActionPerformed
        
        
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(this);
        File f = fc.getSelectedFile();
        openfile(f.toString());
    }//GEN-LAST:event_loadfileActionPerformed

    private void createBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTNActionPerformed
            
       // filldata();
        
        if(invoice_no_field.getText().equals("") || datefiled.getText().equals("") || customerfield.getText().equals("") || totalfield.getText().equals("") ) {
			JOptionPane.showMessageDialog(null, "Please Enter all Fields! ");

		}else {
		//inv_Num_label.setText(invoice_no_field.getText());
                    
//		row[0] = invoice_no_field.getText();
//              	row[1] = datefiled.getText();
//		row[2] = customerfield.getText();
//		row[3] = totalfield.getText();
                    model = (DefaultTableModel) table.getModel();
                    model.addRow(new Object [] {invoice_no_field.getText(),datefiled.getText(),
                                               customerfield.getText(),totalfield.getText() });
		
                
		JOptionPane.showMessageDialog(null, "Data Added Successfully ");


		//model.addRow(row);
		invoice_no_field.setText("");
		datefiled.setText("");
		customerfield.setText("");
		totalfield.setText("");
		}
        
    }//GEN-LAST:event_createBTNActionPerformed

    private void savefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savefileActionPerformed
        save();        // TODO add your handling code here:
    }//GEN-LAST:event_savefileActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
            save();

    }//GEN-LAST:event_saveBTNActionPerformed

    private void deleteBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTnActionPerformed

        int i = table.getSelectedRow();
	model.removeRow(i);
    }//GEN-LAST:event_deleteBTnActionPerformed

    private void CancelBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTnActionPerformed
        invoice_no_field.setText("");
	datefiled.setText("");
	customerfield.setText("");
	totalfield.setText("");
    }//GEN-LAST:event_CancelBTnActionPerformed
public void openfile(String file){
        File path = new File(file);
        try {
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("desktop err");
        }
                
        
    }

public void save(){
    JFileChooser filechooser = new JFileChooser();
        filechooser.showSaveDialog(this);
        File savefile = filechooser.getSelectedFile();
        
        if(savefile!=null){
            
            savefile = new File(savefile.toString()+".xlsx");
            //table.setModel((TableModel) savefile);
            Workbook wb = new SXSSFWorkbook();
            Sheet sheet = wb.createSheet("invoice");
            //table2 = (JTable) wb.getSheet("invoice");
            Row rowcol = sheet.createRow(0);
            
            for (int i = 0; i < table.getColumnCount(); i++) {
                Cell cell = rowcol.createCell(i);
                cell.setCellValue(table.getColumnName(i));
            }
            for (int j = 0; j < table.getRowCount(); j++) {
                Row row = sheet.createRow(j);
                for (int k = 0; k < table.getColumnCount(); k++) {
                    Cell cell = row.createCell(k);
                    if(table.getValueAt(j, k)!=null){
                        cell.setCellValue(table.getValueAt(j, k).toString());
                    }
                }
            }
            try {
                FileOutputStream out = new FileOutputStream(new File(savefile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openfile(savefile.toString());
                
            } catch (FileNotFoundException ex) {
              //  Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("out stream err");
                JOptionPane.showMessageDialog(null, "File Not Found");
            } catch (IOException ex) {
                //Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Wrong File format");

                System.out.println("write err");
            }
             
            
            
        }
        else{
        JOptionPane.showMessageDialog(null, "Error");
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBTn;
    private javax.swing.JButton createBTN;
    private javax.swing.JTextField customerfield;
    private javax.swing.JTextField datefiled;
    private javax.swing.JButton deleteBTn;
    private javax.swing.JTextField invoice_no_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuItem loadfile;
    private javax.swing.JButton saveBTN;
    private javax.swing.JMenuItem savefile;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JTextField totalfield;
    // End of variables declaration//GEN-END:variables
}
